### PR TITLE
Drag and drop file in ace

### PR DESCRIPTION
**Pull request by beyond2void**
We could drag and drop a file from local to our tool now.

### CODE REVIEW

**Comment by beyond2void** [comment]
https://github.com/PaulBredl/config-assistant/assets/51022913/4d91fcda-5cd6-4a75-88ad-1592fbf32992

Effect like this.

**Review by PaulBredl — COMMENTED** [review]
Generally looks nice but I think you can use Vue specific features to make the code more clean (don't know for sure!)
Instead of adding event listeners manually, you should be able to use the Vue event handlers '@drag' and the similar ones.

**Comment by PaulBredl** [comment]
https://learnvue.co/articles/vue-drag-and-drop

Here are examples

**Comment by beyond2void** [comment]
> Generally looks nice but I think you can use Vue specific features to make the code more clean (don't know for sure!) Instead of adding event listeners manually, you should be able to use the Vue event handlers '@drAg' and the similar ones.

That looks nice. I'll try to improve it

**Comment by PaulBredl** [comment]
@beyond2void just a quick reminder that this pull requests still has some todos. They shouldnt take too long,

**Comment by beyond2void** [comment]
> @beyond2void just a quick reminder that this pull requests still has some todos. They shouldnt take too long,

Vue does not has its own drag&drop event. It's actually implemented using the HTML dragdrop methods.
So I don't know if it's still needed to change the style of the code.
Btw, I simplified the code, deleted some unnecessary parts.

**Comment by PaulBredl** [comment]
> > @beyond2void just a quick reminder that this pull requests still has some todos. They shouldnt take too long,
> 
> Vue does not has its own drag&drop event. It's actually implemented using the HTML dragdrop methods. So I don't know if it's still needed to change the style of the code. Btw, I simplified the code, deleted some unnecessary parts.

I will do it real quick

**Comment by Logende** [comment]
> 2023-08-30.16.41.23.mov 
> 
> Effect like this.

looks nice

**Review by PaulBredl — APPROVED** [review]
@beyond2void also check if this is fine

**Comment by beyond2void** [comment]
> @beyond2void also check if this is fine

Thanks for improving. 
I understand now what you meant by "more vue style" 👍

**Pull request merged**
