### PR TITLE
improve search in gui editor

### PR DESCRIPTION
**Pull request by PaulBredl**
- fix search in recursive schemas
- scroll selected element into view

### CODE REVIEW

**Comment by beyond2void** [comment]
https://github.com/PaulBredl/config-assistant/assets/51022913/dac726b3-1f29-49cd-a56c-439136382b21

It seems still a bit buggy.
It still doesn't jump to selected element when object is collapsed.(See video: Pedestriangroup[0].speed)

**Comment by PaulBredl** [comment]
@beyond2void I think now it is really smooth

**Comment by PaulBredl** [comment]
@Logende I don't if you never implemented it or it stopped working, but if I have a property that is too deep, i.e, deeper than the maximum depth, when I select that element in the code editor or with the search functionality, the gui editor does not automatically zoom in until the necessary level.
Did we only talk about this?

**Comment by beyond2void** [comment]
> @beyond2void I think now it is really smooth

The scroll effect is really nice!

**Review by beyond2void — APPROVED** [review]

**Review by Logende — APPROVED** [review]
I like it

**Comment by Logende** [comment]
> @Logende I don't if you never implemented it or it stopped working, but if I have a property that is too deep, i.e, deeper than the maximum depth, when I select that element in the code editor or with the search functionality, the gui editor does not automatically zoom in until the necessary level.
> Did we only talk about this?

Right, yeah we talked about this. It would be an additional feature to zoom into properties if the selected element is below the depth limit. This feature is not yet implemented.

**Comment by beyond2void** [comment]
> @beyond2void I think now it is really smooth

If you try more times with different select elements, it happens sometimes which  it does not scroll into view.

**Pull request merged**
