### PR TITLE
362 remove backend folder

### PR DESCRIPTION
**Pull request by Keyshal-211**

### CODE REVIEW

**Review by PaulBredl — CHANGES_REQUESTED** [review]
Ci pipeline / Github action not working

**Review by PaulBredl — COMMENTED** [review]
To avoid merge conflicts, we should do this at the very end

**Comment by Logende** [comment]
Decision with Minye, Paul and me: 

- Rename tool back to MetaConfigurator because its more catchy/stays more in the mind
- Move frontend/config-assistant to /frontend

**Comment by Logende** [comment]
Will do moving of all files later, to avoid merge conflicts during the current phase.

**Pull request closed without merging**
