### PR TITLE
Cookies Handling WIP!!

### PR DESCRIPTION
**Pull request by Keyshal-211**

### CODE REVIEW

**Comment by Keyshal-211** [comment]
@Logende @PaulBredl may be you can help me in that, I used https://www.npmjs.com/package/vue-cookies, and wrote code but I got Parse error, I tried also with vue cookies next package instead of vue cookies but it is not working. may be can you see the code and help me in that?

**Comment by PaulBredl** [comment]
> 

I wrote in WhatApp that cookies can only have 4KB. did you check if the contents fit into that size? Because they likely do not.

**Comment by PaulBredl** [comment]
only do settings data in the cookie, not file and schema data

**Comment by Keyshal-211** [comment]
@PaulBredl when I change something in settings then I can see updated cookies but when I refresh the page old one is not coming. any idea?

**Comment by Keyshal-211** [comment]
@PaulBredl  written in the cookie what you mean? in console? 
Screenshot 2023-08-28 at 14 19 08

**Comment by PaulBredl** [comment]
> @PaulBredl written in the cookie what you mean? in console? Screenshot 2023-08-28 at 14 19 08

check the cookies of your browser, i have no idea how this works in safari, I only know my browser

**Review by Logende — APPROVED** [review]

**Pull request merged**
